Repository gsasansol/GirlScript-Asansol, pull requests merged in 2022-10, with the labels that each got.

#37 implemented dark mode
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#38 navbar is mobile responsive now
  CONTRIBUTORS
  index.html
  styles.css
Labels: hacktoberfest-accepted

#40 Added article for Introduction to Quantum Bits & Quantum Computing
  CONTRIBUTORS
  components/articles/quantum-computing/assets/image1.gif
  components/articles/quantum-computing/assets/image2.png
  components/articles/quantum-computing/assets/image3.png
  components/articles/quantum-computing/quantum-computing.json
  components/articles/quantum-computing/quantum-computing.markdown
Labels: hacktoberfest-accepted

#42 Added Blogs Folder
  Blogs/blogcard.css
  Blogs/blogcard.html
Labels: hacktoberfest-accepted

#50 fixed the issue
  Assets/asn-junction.jpg
  Resources/blogcard.css
  Resources/blogcard.html
  index.html
  styles.css
Labels: hacktoberfest-accepted

#52 404 page
  404.css
  404.html
  Assets/pic1.png
  CONTRIBUTORS
Labels: hacktoberfest-accepted

#54 changes
  Resources/blogcard.css
Labels: hacktoberfest-accepted

#57 FAQ added
  CONTRIBUTORS
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#60 Pastevents Section added.
  CONTRIBUTORS
  pastevents/css/styles.css
  pastevents/images/alex-kotliarskyi-QBpZGqEMsKg-unsplash.jpg
  pastevents/images/event1.png
  pastevents/images/event2.png
  pastevents/images/event3.png
  pastevents/images/event4.png
  pastevents/index.html
Labels: hacktoberfest-accepted

#58 Document/Roadmap on Artificial Intelligence and Machine Learning
  components/articles/artificial-intelligence/artificial-intelligence.json
  components/articles/artificial-intelligence/artificial-intelligence.markdown
  components/articles/artificial-intelligence/assets/image1.png
  components/articles/artificial-intelligence/assets/image2.png
Labels: hacktoberfest-accepted

#59 Web Development Roadmap
  CONTRIBUTORS
  components/articles/Web Development/Assets/Dino1.jpg
  components/articles/Web Development/Assets/WebDevRoadmap.jpg
  components/articles/Web Development/Web_Dev_roadmap.json
  components/articles/Web Development/Web_Development.md
Labels: hacktoberfest-accepted

#67 cursor changed
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#79 fixed navbar for mobile
  styles.css
Labels: hacktoberfest-accepted

#83 Issue #78 Resolved , Added Dismissable top notification bar
  index.html
  styles.css
Labels: hacktoberfest-accepted

#90 Preloader fixed
  index.html
  styles.css
Labels: hacktoberfest-accepted

#91 Issue #89 Resolved FAQ clickability working properly
  index.html
  styles.css
Labels: hacktoberfest-accepted

#95 Add changes to past event section
  index.html
  styles.css
Labels: hacktoberfest-accepted

#103 Make over of NavBar #96
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#108 fixed color of past event heading, faq heading and header-wave for da…
  index.html
  index.js
Labels: hacktoberfest-accepted

#123 mouse trail added
  index.js
  styles.css
Labels: hacktoberfest-accepted

#126 created favicon for website
  Assets/asn-logo-modified.png
  index.html
Labels: hacktoberfest-accepted

#133 Remove pre-loader scroll
  CONTRIBUTORS
  index.html
Labels: hacktoberfest-accepted

#143 404 changes
  404.css
  404.html
  404page/index.html
  404page/index.js
  404page/style.css
Labels: hacktoberfest-accepted

#144 Added Responsive Footer
  CONTRIBUTORS
  index.html
  styles.css
Labels: hacktoberfest-accepted

#153 Made About Us Section.
  Assets/asn-about-us.jpg
  CONTRIBUTORS
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#160 UI and UX changes
  index.html
  styles.css
Labels: hacktoberfest-accepted

#162 Added Contact-us page sphere dark mode
  CONTRIBUTORS
  index.js
  styles.css
Labels: hacktoberfest-accepted

#164 Update Contributor
  CONTRIBUTORS
Labels: documentation, hacktoberfest-accepted

#163 fix : Fix the contact us section. [fixes #154]
  CONTRIBUTORS
  index.html
  styles.css
Labels: hacktoberfest-accepted

#167 Fix FAQ Picture overflowing and not centering
  index.html
  styles.css
Labels: hacktoberfest-accepted

#172 carousel btns working in mobile
  CONTRIBUTORS
  index.html
Labels: hacktoberfest-accepted

#174 Fixing About Section Bug and Enhancement
  index.html
  styles.css
Labels: hacktoberfest-accepted

#171 Added a Scroll to Top Button
  CONTRIBUTORS
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#191 [GitHub public beta] Created issue template forms
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: documentation, enhancement

#194 modify in blogCard
  CONTRIBUTORS
  Resources/blogcard.css
  Resources/blogcard.html
Labels: hacktoberfest-accepted

#200 past event card & navbar fixed
  CONTRIBUTORS
  components/articles/DevOps Roadmap/DevOps_Roadmap.json
  components/articles/DevOps Roadmap/DevOps_Roadmap.md
  styles.css
Labels: hacktoberfest-accepted

#205 modified about us section
  CONTRIBUTORS
  index.html
  styles.css
Labels: hacktoberfest-accepted

#208 Daniele avolio
  CONTRIBUTORS
  styles.css
Labels: hacktoberfest-accepted

#215 revamped "past events" section
  CONTRIBUTORS
  components/articles/Cryptography Roadmap/Cryptography_Roadmap.json
  components/articles/Cryptography Roadmap/Cryptography_Roadmap.md
  index.html
  index.js
  styles.css
  swiper-bundle.min.css
  swiper-bundle.min.js
Labels: hacktoberfest-accepted

#216 NavBar Fixed for Tablet View
  styles.css
Labels: hacktoberfest-accepted

#221 Fix: Fix the faq section in the dark mode [fixes #220]
  styles.css
Labels: hacktoberfest-accepted

#223 modify past events card in mobile view
  CONTRIBUTORS
  index.html
  styles.css
Labels: hacktoberfest-accepted

#226 Created Our Teams Page
  Assets/team/aaheli2.png
  Assets/team/abir.jpeg
  Assets/team/abir.jpg
  Assets/team/debdeep.jpeg
  Assets/team/jayanta.jpeg
  Assets/team/nidhi.jpeg
  Assets/team/pranay.png
  Assets/team/rohit.jpeg
  Assets/team/saikat.jpeg
  Assets/team/soumali.jpeg
  Assets/team/soumya.jpeg
  Assets/team/souvik.jpeg
  Assets/team/subham.jpeg
  index.html
  styles.css
  team.html
  teamstyle.css
Labels: hacktoberfest-accepted

#227 Updated font family, bg-image gradient and margin
  index.html
  styles.css
Labels: hacktoberfest-accepted

#231 Added content in all the cards of the "resources"
  Resources/resource.html
  components/articles/Cryptography Roadmap/cryptography.jpg
  components/articles/DevOps Roadmap/DevOps-processes.png
  components/articles/dbms-sql/dbms.png
Labels: hacktoberfest-accepted

#233 Added an article on "An insight into Machine Learning"
  Resources/blog_card_machine_learning.html
  components/articles/Machine Learning/Machine-Learning.md
  components/articles/Machine Learning/machine-learning.json
Labels: hacktoberfest-accepted

#241 Add missing top border radius for .card-top
  teamstyle.css
Labels: hacktoberfest-accepted

#244 background gradient added, box hadow added, contact card bg modified
  styles.css
Labels: hacktoberfest-accepted

#246 vertical scrolling added
  CONTRIBUTORS
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#248 Button dark mode added
  index.html
  index.js
  styles.css
Labels: hacktoberfest-accepted

#250 docs for CSS styles added
  docs/README.md
Labels: hacktoberfest-accepted
